### ISSUE TITLE
Account Sidebar: Further Steps

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#3671]
- [x] #3680 (assigned to @Simon-Laux for now)
- [x] context menu backdrop #3643 (@adzialocha)
	- this will solve the small ux bug that you can still trigger the hover menu with your mouse when a context menu is active
- [x] #3668 
- [x] #3670 
- [x] #3675
- [x] cursor pointer for account items (@adzialocha)
- [x] https://github.com/deltachat/deltachat-desktop/issues/3681 (@adzialocha)

## Beyond 1.44

- [x] on open: scroll currently active account into view
  https://github.com/deltachat/deltachat-desktop/pull/4137
- [ ] core: set sync for single accounts https://github.com/deltachat/deltachat-core-rust/pull/5314
    -  after this is done we can  remove the `window.__updateAccountListSidebar` hack, as this new api will replace the `syncAllAccounts` option.
- [X] ~~core: mute accounts? (notification is handled by ui so this would probably just store the setting/option and if we allow time based then revert once the mute time is over?)~~ -> rather "ui.*" setting
- [x] core: Drag and Drop to reorder accounts, needs core support to store position somehow
     - iOS already has move to top, which stores some sort number in the accounts -> https://github.com/deltachat/deltachat-ios/blob/dba6e6e2b3c5424d25403f488bbaf92965c901ff/deltachat-ios/DC/DcAccount.swift#L57
         - a possible downside to storing this in the account's ui config is that it will be exported in backups, I think this should be managed by the account manager and stored in `accounts.toml`
- [x] indicators on top and bottom if there are unread accounts out of screen
  Related: https://github.com/deltachat/deltachat-desktop/pull/4536
- [X] core: ensure there are core events for all cases where the account list is updated to remove the `window.__updateAccountListSidebar` hack
    - the only occurrence that is left of this is for syncAllAccounts setting, so moving the task of removing the hack to the sync setting in core
- [ ] Theming questions: should we make the sidebar themeable? should we allow each account to have it's own theme? some previous discussion can be found In: https://github.com/deltachat/deltachat-desktop/issues/3794

## nice to have
- [ ] Find an even better background image for account deletion

**Comment by farooqkz** [comment]
Regarding, this:

> Drag and Drop to reorder accounts, needs core support to store position somehow

Doesn't core already support some mechanism of saving data no matter what?

**Comment by Simon-Laux** [comment]
> Doesn't core already support some mechanism of saving data no matter what?

there are config keys per account, but not per account manager yet. Also this needs some thinking about how to store positions smartly to not introduce bug where accounts are hidden/missing, maybe seeking of priority number for each account or if we store an order array, then only take it as suggestion and display missing accounts at the end or sth like that.

**Comment by Simon-Laux** [comment]
I could agree an experimental setting to hide account sidebar and one to disable small screen mode.

why experimental:
- hide account sidebar -> the real solution would be a new design where this list is collapsible and has shortcuts
- disable small screen mode -> unless #633 is implemented the cut of chatlist is nothing we want to ship by default, I think small screen mode is what most users want.

**Comment by r10s** [comment]
>  I think this should be managed by the account manager and stored in accounts.toml

ftr, writing to `accounts.toml` is sensitive and was avoided whereever possible even in the past, see https://github.com/chatmail/core/pull/5759#issuecomment-2218120664

looking at [current issues](https://github.com/deltachat/deltachat-desktop/issues/4748) in that area, i cannot agree more to not do more things there as strictly needed.

iirc, there were already ideas around about how to make that possible in a smart way while not using `accounts.toml`

**Comment by Simon-Laux** [comment]
> ftr, writing to accounts.toml is sensitive and was avoided whereever possible also in the past, see https://github.com/chatmail/core/pull/5759#issuecomment-2218120664

we could also have a separate "accounts/accounts_order.toml"/"accounts/accounts_config.toml" file. When we add locked/encrypted accounts, we can not read any config from them directly until they are unlocked.
It makes sense to also be able to store configuration on the Account manager.

**Comment by sadraiiali** [comment]
hello eveyone.
just for info wanted to mention that
 account order is added to the core. -> https://github.com/chatmail/core/pull/6993
and I'm trying to add account order feature on -> https://github.com/deltachat/deltachat-desktop/pull/5279

**Comment by farooqkz** [comment]
Yoooo Ali!

**Comment by nicodh** [comment]
Most of the tasks are completed and https://github.com/chatmail/core/issues/4296 is closed so it should be sufficient what we have
