### ISSUE TITLE
Browser Edition - Remaining To Do

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#4232]
- [x] Background Image #4306
- [X] Themes (without the option for custom themes, as you can easily edit themes when you are using the browser version as you can only start it from development environment anyway, also `--watch-theme` is not necessary for this step) #4304
- [X] backup/key export  #4303
- [ ] support env vars
	- [x] TEST_DIR <- for testing
	- [ ] CERT_DIR <- for testing
	- [ ] DELTACHAT_LOCALE_DIR
- [x] env var / cli option to use test.html instead of main.html
- [ ] support cli options and document somewhere what is and isn't supported
- [ ] improve the hint/message that only one concurrent client is supported (reload button + and use custom dialog because safari does not present alert if you if the tab/window is not focused/active)
- [ ] well known temp folder that gets deleted/cleared when server is closed or started (for tmp file uploads).
- [ ] clear backup export folder on every web server start / shutdown
---
- [ ] express sometimes hangs after a burst of requests to blobfiles - investigate that function -> but maybe thats also a lock in core? -> can be easily triggered by sending many files with (todo insert pr number of my new pr here) - but after while it allows me to reload the page and then works again.

**Comment by r10s** [comment]
we will create issues on point if needed
