### ISSUE TITLE
Refactor Message Rendering 

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat/deltachat-desktop#536]
### In order to add/fix:
In the message-list/ chat view:

- [ ] Scrolling #477
- [ ] Proper Lazy Loading / Infinity scroll list
- [ ] Jumping to specific Messages (necessary for 'reply to message')
- [ ] mark read refinements #458 
- [ ] indicator on where unread messages begin
- [ ] If scrolling through message history and a new messages comes in, don't jump to the new message #712 
- [ ] Chat messages should start above message input in chats with less messages #381
- [ ] only mark messages are read when they are visible in view port #458

In the Messages themselves:
- [ ] To add Markdown support (will be removed again with #1254)
- [x] Simplify the Emoji message gets bigger when it only contains a few emojis code

Feel free to add related issues/things. 

Related: https://github.com/deltachat/deltachat-desktop/issues/885
Related https://github.com/deltachat/deltachat-desktop/issues/937

**Comment by hpk42** [comment]
On Sat, Jan 05, 2019 at 11:25 -0800, Simon Laux wrote:
> - [ ] To add Markdown support #491

i'd leave "mark down support" as a separate issue as it needs cross-app 
support i'd think. Maybe we could use some nice Rust markdown renderer 
once we can build Rust with core (cc @dignifiedquire)? 
one general idea is that all more involved parsing of things coming 
from the outside (network, pgp and mime + eg markdown) moves
to Rust over time.

**Comment by dignifiedquire** [comment]
unclear if I agree with this, for some platforms like ios you would go from markdown to visual representation, without using html. so I don‘t think this is sth that has to be in core

**Comment by hpk42** [comment]
On Sat, Jan 05, 2019 at 14:26 -0800, Lars-Magnus Skog wrote:
> > unclear if I agree with this, for some platforms like ios you would go from markdown to visual representation, without using html. so I don‘t think this is sth that has to be in core
> 
> Makes sense. Lets keep core lean and mean.

if we do add markdown support to desktop then let's
at least keep it minimal (also for security reasons -- i.e.
no arbtirary inlined html etc.) and make sure there is a viable
path how this can work, at least be viewed on android and 
ios as well.

FWIW, before markdown, i'd like to have nice multi-line editing 
of messages in desktop btw ;)

**Comment by Jikstra** [comment]
>  FWIW, before markdown, i'd like to have nice multi-line editing of messages in desktop btw ;)

Please, someone, do it! :D

**Comment by Simon-Laux** [comment]
> > FWIW, before markdown, i'd like to have nice multi-line editing of messages in desktop btw ;)
> 
> Please, someone, do it! :D

We secretly wait for you to do it...:slightly_smiling_face: pssst.... 🤫  
xD

**Comment by r10s** [comment]
i'd also like to note that i would postpone the markdown support.

starting with markdown support will probably open a bunch of new bugs and dependencies, also wrt cross-platform support.

and i think, just now, there are already enough issues, no need to introduce new ones fast :)

**Comment by ralphtheninja** [comment]
> and i think, just now, there are already enough issues, no need to introduce new ones fast :)

Good point. I agree 100%. We have enough issues already.

**Comment by r10s** [comment]
this issue seems to be stale. if there are concrete bugs, we should file them in separate issues.

**Comment by Simon-Laux** [comment]
Its a collection issue for what needs to be done in the message view

**Comment by r10s** [comment]
but it seems to be stale. so, i think, we should add more concrete issues for _concrete_ problems with the message list.

**Comment by Simon-Laux** [comment]
I only recently updated it

**Comment by r10s** [comment]
if it helps, we can reopen it. 

i just thought that several points in the list are not really something that will be done reasonably in the near future, and definitely not for a 1.0 - and other points are already fixed long time ago and the list is not updated. so, i think there is not much worth in it. in general, i think it is hard to maintain such lists for a longer period :)
